{{- if .Values.global.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  automountServiceAccountToken: {{ .Values.global.rbac.automountServiceAccountToken }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-pod-reader
	rules:
	- apiGroups: [""]
	  resources: ["pods"]
	  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-read-pods
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-pod-reader 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
