{{- if (eq "statefulset" .Values.global.deploymentType) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: {{ .Release.Namespace }}
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: local

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-1
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-2
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-3
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data3"
{{- end }}
