global:
  image:
    image: vigneshsweekaran/easyclaim-frontend:32011
    tag: 32011
  replicas: 2

service:
  type: NodePort
  nodePort: 32012

hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50