{{- if (eq "deployment" .Values.global.deploymentType) }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
data:
  MYSQL_DATABASE: test
{{- end }}