{{- if (eq "deployment" .Values.global.deploymentType) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
{{- end }}